name: "KOOL pack site  Infra Destruction"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Your environment"
        required: false
        type: string
        default: "production"

      confirm_destroy:
        description: "Confirm infrastructure destruction"
        required: true
        type: choice
        options:
          - "yes"
          - "no"

jobs:
  delete:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:

      - name: "Check Environment Variable"
        if: ${{ github.event.inputs.environment == 'production' }}
        run: echo "Environment is production"

      - name: "Check Environment Variable"
        if: ${{ github.event.inputs.environment == 'development' }}
        run: echo "Environment is development"
      
      - name: "Check Environment Variable"
        if: ${{ github.event.inputs.environment == 'testing' }}
        run: echo "Environment is testing"

      - name: "Unknown Environment"
        if: ${{ github.event.inputs.environment != 'production' && github.event.inputs.environment != 'development' && github.event.inputs.environment != 'testing' }}
        run: echo "Unknown environment specified"
