name: "KOOL pack site  Infra Destruction"

on:
  workflow_dispatch:

    inputs:

      environment:
        description: "Select Your evironment"
        required: false
        type: string
        default: "production"

      confirm_destroy:
        description: "Confirm infrastructure destruction"
        required: true
        type: choice
        options:
          - "yes"
          - "no"
jobs:

  delete:
    runs-on: ubuntu-latest

    steps:
      - name: "os details"
        run: |
          cat /etc/os-release
          whoami

