name: "KOOL pack site  Infra Destruction"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Your environment"
        required: false
        type: string
        default: "production"

      confirm_destroy:
        description: "Confirm infrastructure destruction"
        required: true
        type: choice
        options:
          - "yes"
          - "no"

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:

      - name: "Print Input Variables"
        run: |
          echo "Event: ${{github.event}}"
          echo "Inputs: ${{github.inputs}}"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Confirm Destroy: ${{ github.event.inputs.confirm_destroy }}"

